version: "3.8"
services:
  graph:
    build: .
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      - kafka
      - postgres
  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: organsyncgraph
      POSTGRES_USER: organsync
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
