spring:
  datasource:
    url: jdbc:h2:mem:organsyncgraphdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: organsync-graph-group
  h2:
    console:
      enabled: true
server:
  port: 8085
